apiVersion: v1
kind: Service
metadata:
  name: service-equix-website
  namespace: website
  labels:
    app: equix-website
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31582
  selector:
    app: equix-website

---

