
export const eventEmitter = {
    CHANGE_MAIN_STATE: 'CHANGE_MAIN_STATE',
    CHANGE_CONNECTION: 'CHANGE_CONNECTTION',
    CHANGE_CONNECTION_STREAM: 'CHANGE_CONNECTION_STREAM',
    ENTER_PIN_SUCCESS: 'ENTER_PIN_SUCCESS',
    CHECK_ORDER_STATUS_BY_NOTI: 'CHECK_ORDER_STATUS_BY_NOTI',
    CHANGE_CONNECTION_AFTER_RENEW_TOKEN: 'CHANGE_CONNECTION_AFTER_RENEW_TOKEN',
    REFRESH_DATA_ACCOUNT: 'REFRESH_DATA_ACCOUNT'
};

export const emitter = {
    MAIN_FORM: 'MAIN_FORM',
    CHECK_CONNECTION: 'CHECK_CONNECTION',
    PIN_INPUT: 'PIN_INPUT',
    CHECK_ORDER_STATUS: 'CHECK_ORDER_STATUS',
    STREAMING_ACCOUNT_DATA: 'STREAMING_ACCOUNT_DATA',
    CHECK_CONNECTION_STREAM: 'CHECK_CONNECTION_STREAM'
};

export const eventEmitterRefresh = {
    CLICK_TO_REFRESH_STATE: 'CLICK_TO_REFRESH_STATE'
};

export const emitterRefresh = {
    CLICK_TO_REFRESH: 'CLICK_TO_REFRESH'
};

export const eventEmitterChangeAccount = {
    CHANGE_ACCOUNT_STATE: 'CHANGE_ACCOUNT_STATE'
};

export const emitterChangeAccount = {
    CHANGE_ACCOUNT: 'CHANGE_ACCOUNT'
}
