export default {
    'XNYS': { label: 'XNYS', display: 'NYSE', flag: 'us' },
    'XASE': { label: 'XASE', display: 'AMEX', flag: 'us' },
    'ARCX': { label: 'ARCX', display: 'ARCX', flag: 'us' },
    'BATS': { label: 'BATS', display: 'BATS', flag: 'us' },
    'IEXG': { label: 'IEXG', display: 'IEXG', flag: 'us' },
    'XNAS': { label: 'XNAS', display: 'NASDAQ', flag: 'us' },
    'NYSE': { label: 'XNYS', display: 'NYSE', flag: 'us' },
    'AMEX': { label: 'XASE', display: 'AMEX', flag: 'us' },
    'NASDAQ': { label: 'XNAS', display: 'NASDAQ', flag: 'us' },
    'ASX': { label: 'ASX', display: 'ASX', flag: 'au' },
    'ASX:BB': { label: 'ASX:BB', display: 'ASX BookBuild', flag: 'au' },
    'ASX:CP': { label: 'ASX:CP', display: 'ASX CentrePoint', flag: 'au' },
    'ASX:TM': { label: 'ASX:TM', display: 'ASX TradeMatch Market', flag: 'au' },
    'ASX:TM:D': { label: 'ASX:TM:D', display: 'ASX TradeMatch Derivatives Market', flag: 'au' },
    'ASX:TM:E1': { label: 'ASX:TM:E1', display: 'ASX TradeMatch Equity Market 1 (A-B)', flag: 'au' },
    'ASX:TM:E2': { label: 'ASX:TM:E2', display: 'ASX TradeMatch Equity Market 2 (C-F)', flag: 'au' },
    'ASX:TM:E3': { label: 'ASX:TM:E3', display: 'ASX TradeMatch Equity Market 3 (G-M)', flag: 'au' },
    'ASX:TM:E4': { label: 'ASX:TM:E4', display: 'ASX TradeMatch Equity Market 4 (N-R)', flag: 'au' },
    'ASX:TM:E5': { label: 'ASX:TM:E5', display: 'ASX TradeMatch Equity Market 5 (S-Z)', flag: 'au' },
    'ASX:TM:I': { label: 'ASX:TM:I', display: 'ASX TradeMatch Index Market', flag: 'au' },
    'ASX:TM:ID': { label: 'ASX:TM:ID', display: 'ASX TradeMatch Index Derivatives Market', flag: 'au' },
    'ASX:TM:IR': { label: 'ASX:TM:IR', display: 'ASX TradeMatch Interest Rate Market', flag: 'au' },
    'ASX:TM:PRV': { label: 'ASX:TM:PRV', display: 'ASX TradeMatch Private Market', flag: 'au' },
    'ASX:TM:QD': { label: 'ASX:TM:QD', display: 'ASX TradeMatch Quote Display Board', flag: 'au' },
    'ASX:TM:TST': { label: 'ASX:TM:TST', display: 'ASX TradeMatch Practice Market', flag: 'au' },
    'ASX:TM:W': { label: 'ASX:TM:W', display: 'ASX TradeMatch Warrants Market', flag: 'au' },
    'ASX:PM:E1': { label: 'ASX:PM:E1', display: 'ASX PureMatch Equity Market 1 (A-B)', flag: 'au' },
    'ASX:PM:E2': { label: 'ASX:PM:E2', display: 'ASX PureMatch Equity Market 2 (C-F)', flag: 'au' },
    'ASX:PM:E3': { label: 'ASX:PM:E3', display: 'ASX PureMatch Equity Market 3 (G-M)', flag: 'au' },
    'ASX:PM:E4': { label: 'ASX:PM:E4', display: 'ASX PureMatch Equity Market 4 (N-R)', flag: 'au' },
    'ASX:PM:E5': { label: 'ASX:PM:E5', display: 'ASX PureMatch Equity Market 5 (S-Z)', flag: 'au' },
    'ASX:V': { label: 'ASX:V', display: 'ASX VolumeMatch', flag: 'au' },
    'CXA': { label: 'CXA', display: 'CXA', flag: 'au' },
    'CXA::FP': { label: 'CXA::FP', display: 'Chi-X Australia Far-Point Market', flag: 'au' },
    'CXA::LI': { label: 'CXA::LI', display: 'Chi-X Australia Limit Market', flag: 'au' },
    'CXA::MC': { label: 'CXA::MC', display: 'Chi-X Australia Market-on-Close Market', flag: 'au' },
    'CXA::MP': { label: 'CXA::MP', display: 'Chi-X Australia Mid-Point Market', flag: 'au' },
    'CXA::NP': { label: 'CXA::NP', display: 'Chi-X Australia Near-Point Market', flag: 'au' },
    'NSX': { label: 'NSX', display: 'Australian National Stock Exchange Main', flag: 'au' },
    'NSX::COM': { label: 'NSX::COM', display: 'Australian National Stock Exchange Community Banks', flag: 'au' },
    'NSX::CRP': { label: 'NSX::CRP', display: 'Australian National Stock Exchange Industrial', flag: 'au' },
    'NSX::DBT': { label: 'NSX::DBT', display: 'Australian National Stock Exchange Debt', flag: 'au' },
    'NSX::MIN': { label: 'NSX::MIN', display: 'Australian National Stock Exchange Mining & Energy', flag: 'au' },
    'NSX::PROP': { label: 'NSX::PROP', display: 'Australian National Stock Exchange Certified Property', flag: 'au' },
    'NSX::PRP': { label: 'NSX::PRP', display: 'Australian National Stock Exchange Property', flag: 'au' },
    'NSX::RST': { label: 'NSX::RST', display: 'Australian National Stock Exchange Restricted', flag: 'au' },
    'NSX:SV': { label: 'NSX:SV', display: 'SIM-VSE', flag: 'au' },
    'NSX:SP:EQY': { label: 'NSX:SP:EQY', display: 'South Pacific Stock Exchange Equities', flag: 'au' },
    'NSX:SP:RST': { label: 'NSX:SP:RST', display: 'South Pacific Stock Exchange Restricted', flag: 'au' },
    'NZX': { label: 'NZX', display: 'NZX Main Board', flag: 'au' },
    'NZX::NXT': { label: 'NZX::NXT', display: 'NZX NXT Market', flag: 'au' },
    'NZX::SPEC': { label: 'NZX::SPEC', display: 'NZX', flag: 'au' },
    'NZX::FSM': { label: 'NZX::FSM', display: 'NZX Fonterra Shareholders Market', flag: 'au' },
    'NZX::I': { label: 'NZX::I', display: 'NZX Index Market', flag: 'au' },
    'NZX::DX': { label: 'NZX::DX', display: 'NZX Debt Market', flag: 'au' },
    'NZX::AX': { label: 'NZX::AX', display: 'NZX Alternate Market', flag: 'au' },
    'NZX::DF': { label: 'NZX::DF', display: 'NZX Derivative Futures', flag: 'au' },
    'NZX::DO': { label: 'NZX::DO', display: 'NZX Derivative Options', flag: 'au' },
    'NZX::IF': { label: 'NZX::IF', display: 'NZX Index Futures', flag: 'au' },
    'NZX:FX:DO': { label: 'NZX:FX:DO', display: 'NZ Futures & Options Derivative Options', flag: 'au' },
    'NZX:FX:DF': { label: 'NZX:FX:DF', display: 'NZ Futures & Options Derivative Futures', flag: 'au' },
    'NZX:FX:EO': { label: 'NZX:FX:EO', display: 'NZ Futures & Options Equity Options', flag: 'au' },
    'NZX:FX:IF': { label: 'NZX:FX:IF', display: 'NZ Futures & Options Index Futures', flag: 'au' },
    'NZX:FX:MO': { label: 'NZX:FX:MO', display: 'NZ Futures & Options Milk Options', flag: 'au' },
    'ASX:ASX': { label: 'ASX:ASX', display: 'ASX', flag: 'au' },
    'ASX:ASXCP': { label: 'ASX:ASXCP', display: 'ASXCP', flag: 'au' },
    'CXA:qCXA': { label: 'CXA:qCXA', display: 'qCXA', flag: 'au' },
    'CXA:CXACP': { label: 'CXA:CXACP', display: 'CXACP', flag: 'au' },
    'N:qCXA': { label: 'N:qCXA', display: 'qCXA', flag: 'au' },
    'ASX:BESTMKT': { label: 'ASX:BESTMKT', display: 'BESTMKT', flag: 'au' },
    'ASXCP': { label: 'ASXCP', display: 'ASXCP', flag: 'au' },
    'CXACP': { label: 'CXACP', display: 'CXACP', flag: 'au' },
    'qCXA': { label: 'qCXA', display: 'qCXA', flag: 'au' },
    'BESTMKT': { label: 'BESTMKT', display: 'BESTMKT', flag: 'au' },
    'AXW:AXW': { label: 'AXW:AXW', display: 'ASX', flag: 'au' },
    'CXA:CXA': { label: 'CXA:CXA', display: 'CXA', flag: 'au' },
    'AXW:CXA': { label: 'AXW:CXA', display: 'CXA', flag: 'au' },
    'AXW:ASX': { label: 'AXW:ASX', display: 'AXW', flag: 'au' },
    'AXW': { label: 'AXW', display: 'AXW', flag: 'au' },
    'N:FIXED CO': { label: 'N:FIXED CO', display: 'FIXED CO', flag: 'au' }
}
