export default {
    BEFORE_LOGIN: 'BEFORE_LOGIN',
    LOGIN: 'LOGIN',
    SET_PIN: 'SET_PIN',
    VERIFY_PIN: 'VERIFY_PIN',
    AFTER_LOGIN: 'AFTER_LOGIN',
    AFTER_FORGOT_PIN: 'AFTER_FORGOT_PIN',
    CHECK_PIN: 'CHECK_PIN',
    CHECK_PIN_LOGIN: 'CHECK_PIN_LOGIN'
};
