/* eslint-disable import/prefer-default-export */

export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_DATA_NEW = 'LOAD_DATA_NEW';
export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR';
export const DATA_PRICE_SUCESS = 'RESPONSE_DATA_PRICE';
export const DATA_PRICE_SUCESS_INDICES = 'DATA_PRICE_SUCESS_INDICES';
export const USER_SYMBOL_RESPONSE = 'USER_SYMBOL_RESPONSE';
export const USER_SYMBOL_INDICES_RESPONSE = 'USER_SYMBOL_INDICES_RESPONSE';
export const DATA_PRICE_SUCESS_BY_SYMBOL = 'DATA_PRICE_SUCESS_BY_SYMBOL';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_ERROR_WITH_ACCOUNT_INACTIVE = 'LOGIN_ERROR_WITH_ACCOUNT_INACTIVE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
