export default {
    'error_code_1100': 'Invalid symbol',
    'error_code_1101': 'Invalid side',
    'error_code_1102': 'Invalid quantity',
    'error_code_1103': 'Quantity must be greater than 0',
    'error_code_1104': 'Invalid order type',
    'error_code_1105': 'Invalid condition',
    'error_code_1106': 'Invalid limit price',
    'error_code_1107': 'Invalid trigger price',
    // 'error_code_1108': 'Stop price cannot be greater than bid price',
    // 'error_code_1109': 'Stop price cannot be less than offer price',
    // 'error_code_1110': 'Stop price cannot be less than limit price',
    // 'error_code_1111': 'Stop price cannot be greater than limit price',
    'error_code_1112': 'Invalid duration',
    'error_code_1113': 'Invalid exchange',
    'error_code_1200': 'Not available to trade',
    'error_code_1201': 'Not available to trade',
    'error_code_1300': 'Account is not enabled to trade',
    // 'error_code_1301': 'Account is not enabled to trade AU markets',
    // 'error_code_1302': 'Account is not enabled to trade US markets',
    'error_code_1305': 'Account is not enabled to trade',
    'error_code_1306': 'Account is not enabled to trade AU markets',
    'error_code_1307': 'Account is not enabled to trade US markets',
    'error_code_1400': 'Account is not enabled to trade US markets',
    // 'error_code_1401': 'Account is not enabled to buy US securities',
    'error_code_1402': 'Account is not enabled to trade AU markets',
    'error_code_1403': 'Account is not enabled to buy AU securities',
    'error_code_1404': 'Account is not enabled to buy US markets',
    'error_code_1405': 'Account is not enabled to buy US securities',
    'error_code_1500': 'Not available to trade',
    'error_code_1501': 'Order type is not supported',
    'error_code_1502': 'Order type is not supported',
    'error_code_1503': 'Order type is not supported',
    'error_code_1504': 'Duration is not supported',
    'error_code_1505': 'Duration is not supported',
    'error_code_1506': 'Order value too small',
    'error_code_1507': 'Order value too small',
    'error_code_1508': 'Order value too big',
    'error_code_1509': 'Order value too big',
    'error_code_1510': 'The sell order is greater than your available holdings',
    'error_code_1511': 'Not available to trade',
    'error_code_1512': 'Duration is not supported',
    'error_code_1513': 'Duration is not supported',
    'error_code_1514': 'Duration is not supported',
    'error_code_1515': 'Duration is not supported',
    'error_code_1516': 'Trading market is not supported',
    'error_code_1517': 'Trading market is not supported',
    'error_code_1518': 'The sell order is greater than your available holdings',
    'error_code_1519': 'Not available to trade',
    'error_code_1520': 'Order type is not supported',
    'error_code_1521': 'Order type is not supported',
    'error_code_1522': 'Order value too small',
    'error_code_1523': 'Order value too small',
    'error_code_1524': 'Order value too big',
    'error_code_1525': 'Order value too big',
    'error_code_1526': 'Trigger price cannot be less than offer price',
    'error_code_1527': 'Trigger price cannot be less than offer price',
    'error_code_1528': 'Trigger price cannot be greater than limit price',
    'error_code_1529': 'Trigger price cannot be greater than bid price',
    'error_code_1530': 'Trigger price cannot be greater than bid price',
    'error_code_1531': 'Trigger price cannot be less than limit price',
    'error_code_1532': 'Trigger price cannot be less than offer price',
    'error_code_1533': 'Trigger price cannot be less than offer price',
    'error_code_1534': 'Trigger price cannot be greater than limit price',
    'error_code_1535': 'Trigger price cannot be greater than bid price',
    'error_code_1536': 'Trigger price cannot be greater than bid price',
    'error_code_1537': 'Trigger price cannot be less than limit price',
    'error_code_1538': 'Exchange is not supported',
    'error_code_1539': 'Order type is not supported',
    'error_code_1540': 'Order type is not supported',
    'error_code_1541': 'Order type is not supported',
    'error_code_1542': 'Order type is not supported',
    'error_code_1543': 'Order type is not supported',
    'error_code_1544': 'Order type is not supported',
    'error_code_1545': 'Order type is not supported',
    'error_code_1546': 'Duration is not supported',
    'error_code_1547': 'Duration is not supported',
    'error_code_1548': 'Duration is not supported',
    'error_code_1549': 'Duration is not supported',
    'error_code_1550': 'Duration is not supported',
    'error_code_1551': 'Duration is not supported',
    'error_code_1552': 'Duration is not supported',
    'error_code_1600': 'Cannot get market price ',
    'error_code_1601': 'Insufficient cash to trade',
    'error_code_1602': 'Cannot get market price ',
    'error_code_1603': 'Insufficient cash to modify the order',
    'error_code_1604': 'Cannot get currency exchange rate',
    'error_code_1605': 'Cannot get market price ',
    'error_code_1606': 'Insufficient cash to trade',
    'error_code_1607': 'Failed to deposit',
    'error_code_1608': 'Cannot get currency exchange rate',
    'error_code_1609': 'Cannot get market price ',
    'error_code_1610': 'Insufficient cash to modify the order',
    'error_code_1611': 'Failed to deposit',
    'error_code_1700': 'Cannot be connected server',
    'error_code_2000': 'Unknown error',
    'error_code_2004': 'This email format is not recognized. Please check and try again.',
    'error_code_2054': 'Internal error',
    'error_code_2061': 'Please wait a minute and reset password again',
    'error_code_2062': 'Login was unsuccessful',
    'error_code_2087': 'Invalid upload file format. Operator API Access has been supposed to manage all accounts.',
    'error_code_3006': 'Order type not support',
    'error_code_3007': 'Invalid date',
    'error_code_Account': 'Account is not existed',
    'error_code_Account.DailyNet': 'Account daily net value would be exceeded',
    'error_code_Account.DailyGross': 'Account daily gross value would be exceeded',
    'error_code_Authority': 'User does not have permission to trade',
    'error_code_Connection': 'Trading requires a secure connection',
    'error_code_Details': 'No order details were provided',
    'error_code_Error': 'An undefined server error occurred',
    'error_code_Exchange': 'Invalid or not existed Exchange',
    'error_code_Order': 'The given Order ID for a cancel or amend is invalid',
    'error_code_Operation': 'The operation is not supported for this Order',
    'error_code_Retry': '"A temporary error occurred, please retry"',
    'error_code_Route': 'A routing algorithm was not supplied',
    'error_code_Route.Algorithm': 'Not existed routing algorithm',
    'error_code_Route.Market': 'Invalid or not existed Trading Market',
    'error_code_Route.Symbol': 'The symbol cannot be routed to the target Trading Market',
    'error_code_Status': 'The state of order can not be changed',
    'error_code_Style': 'Order Style must be provided. If amending, it must match the Order being amended',
    'error_code_Submitted': 'A fault occurred after the Order was submitted to the Exchange. The Order may have been successfully processed. Please check the Orders subscription',
    'error_code_Symbol': 'Selected symbol is invalid',
    'error_code_Symbol.Authority': 'Current use does not have permission to trade the selected symbol',
    'error_code_Symbol.Status': 'The target symbol is not in a state where the Order operation is supported',
    'error_code_TotalValue.Balance': 'Not enough funds to cover this Order',
    'error_code_TotalValue.Maximum': 'Greater than the maximum allowed value',
    'error_code_ExpiryDate': 'Expiry date is invalid',
    'error_code_HiddenQuantity': 'Hidden quantity is out of range or invalid',
    'error_code_HiddenQuantity.Symbol': 'Not supported hidden quantity by this Symbol',
    'error_code_LimitPrice': 'Limit price is out of range or invalid',
    'error_code_LimitPrice.Distance': 'Limit price is too far from the market',
    'error_code_LimitPrice.Given': 'Limit price must be empty',
    'error_code_LimitPrice.Maximum': 'Limit price is above the maximum ',
    'error_code_LimitPrice.Missing': 'Limit price is required ',
    'error_code_MinimumQuantity': 'Minimum quantity is out of range or invalid',
    'error_code_MinimumQuantity.Symbol': 'Minimum quantity is not supported ',
    'error_code_OrderType': 'Order type is invalid',
    'error_code_OrderType.Market': 'Order type is not supported by the Trading Market',
    'error_code_OrderType.Status': 'Order type is not supported in this Trading State',
    'error_code_OrderType.Symbol': 'Symbol does not support this order type',
    'error_code_Side': 'Invalid side of the Market',
    'error_code_Side.Maximum': 'Excessive amount of open orders on this side',
    'error_code_TotalQuantity': 'Visible and hidden quantities are both zero',
    'error_code_TotalQuantity.Minimum': 'Order is below the minimum value',
    'error_code_TotalQuantity.Holdings': 'Sell order is greater than available holdings',
    'error_code_Validity': 'Invalid validity period',
    'error_code_Validity.Symbol': 'Validity period is not supported by this Symbol',
    'error_code_VisibleQuantity': 'Visible quantity is out of range or invalid',
    'error_code_UnitType': 'invalid unit type',
    'error_code_UnitAmount': 'Out of range unit amount',
    'error_code_Currency': 'Unit Type need a valid currency',
    'error_code_Flags.PDS': 'Flag "PDS" must be set',
    'error_code_TotalQuantity.Maximum': 'Total quantity is above the maximum allowed',
    'error_code_Internal.AccessDenied': 'Denied access internal component ',
    'error_code_Internal.Authority': 'User authority details are not properly setup',
    'error_code_Internal.Database': 'Unavailable database ',
    'error_code_Internal.Error': 'An undefined error occurred',
    'error_code_Internal.Symbol': 'This symbol can not be traded in the selected exchange',
    'error_code_Internal.NotFound': 'A required piece of data was not found',
    'error_code_Internal.Path': 'Server could not find a path to trade this Symbol',
    'error_code_Internal.Service': 'Unavailable internal service ',
    'error_code_TradingIsHalted': 'Trading is halted',
    'error_code_Internal.Unavailable': 'Unexpectedly unavailable internal component',
    'error_code_Timeout': 'Timeout occurred while processing the request',
    'error_code_TIMEOUT': 'Time out occured while processing request',
    'error_code_Cancelled By Exchange': 'Order was cancelled by Exchange',
    'error_code_Cancelled By User': 'Order was cancelled by User',
    'error_code_INVALID_ORDER': 'Invalid order',
    'error_code_SYMBOL_INVALID': 'Invalid symbol',
    'error_code_Service is not avaiable': 'Service is not available',
    'error_code_PlaceMarketOrderTimeOut': 'Market order is time out',
    'error_code_Order is Expired': 'Order is expired',
    'error_code_Validity.FillOrKill': 'Order is killed due to not filled (FillorKill)',
    'error_code_Internal Retry': 'Service is not available',
    'error_code_Disconnected.Paritech': 'Interrupted connection to the Exchange',
    'error_code_Untradedeletes': 'Banned due to too many untraded deletes',
    'error_code_Operation TimeOut': 'Operation is time out',
    'error_code_Authority.Subcribe': 'Authority Subcribe',
    'error_code_Order.Error': 'Order Error',
    'error_code_"Order.Retry"': 'Order Retry',

    'error_code_AF_ERROR_NEW_ORDER': 'Insufficient cash to trade',
    'error_code_AF_ERROR_MODIFY_ORDER': 'Insufficient cash to modify the order',

    'error_code_ACCOUNT_LOCKED': 'Saxo account is locked',
    'error_code_ACCOUNT_NOT_EXIST': 'Account is not supported to trade international stock',
    'error_code_ACCOUNT_NOT_MAPPING': 'Account is not supported to trade international stocks',
    'error_code_ACCOUNT_NULL': 'Invalid Account ID',
    'error_code_AF_ERR': 'Insufficient cash to trade',
    'error_code_AF_ERR_AMEND': 'Insufficient cash to modify the order',
    'error_code_BOOKING_TYPE_CUSTOM_NULL': 'Invalid booking type custom',
    'error_code_CLORDID_NULL': 'Invalid Client Order ID',
    'error_code_CURRENCY_NULL': 'Invalid currency ',
    'error_code_DATA_EXIST': 'Data exist',
    'error_code_DEPOSIT_FAILED': 'Failed to deposit',
    'error_code_ERR_CANNOT_GET_MARKET_PRICE': 'Cannot get market price ',
    'error_code_ERR_CANNOT_GET_RATE': 'Cannot get currency exchange rate',
    'error_code_ERROR': 'Error',
    'error_code_EX_DESTINATION_NULL': 'Invalid exchange',
    'error_code_FIX_NOT_CONNECTED': 'Cannot be connected server',
    'error_code_GET_FAILED': 'Failed to get information',
    'error_code_HAN_NULL': 'Invalid Handllnst',
    'error_code_INFO_REDUNDANT': 'Info redundant',
    'error_code_INSERT_FAILED': 'Failed to insert',
    'error_code_INTERNAL_ERROR': 'Internal error',
    'error_code_INVAILID_POSITION_HOLDING': 'The sell order is greater than your available holdings',
    'error_code_ACCOUNT_NOSAXOTRADING': 'Account is not supported to trade international stocks',
    'error_code_CLOSE_ONLY_POSITION': 'Account is not supported to buy international stocks',
    'error_code_INVALID_MAPPING': 'Invalid mapping',
    'error_code_INVALID_PARAMS': 'Invalid parameter',
    'error_code_INVALID_RESPONSE': 'Invalid response',
    'error_code_INVALID_SYMBOL': 'Invalid symbol',
    'error_code_INVALID_USER': 'Invalid user',
    'error_code_ISIN_CODE_NULL': 'Invalid ISIN',
    'error_code_MISSING_LIMIT_PRICE': 'Invalid limit price ',
    'error_code_MISSING_STOP_PRICE': 'Invalid trigger price ',
    'error_code_NOT_EXIST': 'Invalid information',
    'error_code_NOTHING_CHANGED': 'Nothing has been changed',
    'error_code_ON_BEHALF_OF_COMP_ID_NULL': 'Invalid On behalf of comp ID',
    'error_code_ORDER_CAN_NOT_MODIFY': 'Order cannot be modified',
    'error_code_ORDER_NOT_EXIST': 'Order is not exist',
    'error_code_ORDER_REQUEST_NULL': 'Invalid order request',
    'error_code_ORDER_TYPE_INVALID': 'Invalid order type',
    'error_code_ORDQTY_NULL': 'Invalid quantity',
    'error_code_ORDTYPE_NULL': 'Invalid order type',
    'error_code_PARAM_INVALID': 'Invalid parameter',
    'error_code_PARAM_IS_NULL': 'Invalid parameter',
    'error_code_PRICE_NOT_NEGATIVE': 'Invalid price',
    'error_code_PRODUCT_NULL': 'Invalid product',
    'error_code_QUERY_INVALID': 'Invalid query',
    'error_code_SECURITY_ID_NULL': 'Invalid ISIN',
    'error_code_SECURITY_TYPE_NULL': 'Invalid security type',
    'error_code_SEND_ORDER_TO_SYNCSERVICE_FAILE': 'Failed to request',
    'error_code_SIDE_NULL': 'Invalid side',
    'error_code_SUCCESS': 'Sucessfully',
    'error_code_SYMBOL_NULL': 'Invalid symbol',
    'error_code_TIME_IN_FORCE_NULL': 'Invalid duration',
    'error_code_TRANSACTION_NULL': 'Invalid transaction time',
    'error_code_UNAUTHORIZED': 'Unauthorized',
    'error_code_UNKNOWN_ERROR': 'Unknown error',
    'error_code_UPDATE_FAILED': 'Failed to update',
    'error_code_UPDATE_REQUEST_ORDER_FAILE': 'Failed to update order\'s information',
    'error_code_USER_NOT_MAPPING': 'Invalid user',
    'error_code_VALIDATE_FAILED': 'Invalid input',
    'error_code_VALUE_NULL': 'Invalid input',
    'error_code_ACCOUNT_CAN_NOT_CHANGE': '"ERROR: Trading Status cannot be changed to No Saxo Trading due to Saxo Account Value is not ZERO"',
    'error_code_ORDER_NOT_SYNC': 'Order is not synchronize'
};
