export default {
    STOP: 'STOP_ORDER',
    STOPLOSS: 'STOPLOSS_ORDER',
    LIMIT_SAXO: 'LIMIT_ORDER',
    MARKET_SAXO: 'MARKET_ORDER',
    STOPLOSS_SAXO: 'STOPLOSS_ORDER',
    LIMIT: 'LIMIT_ORDER',
    MARKET: 'MARKET_ORDER',
    MARKETTOLIMIT: 'MARKETTOLIMIT_ORDER',
    TRAILINGSTOP: 'TRAILINGSTOP_ORDER',
    TRAILINGSTOPLIMIT: 'TRAILINGSTOPLIMIT_ORDER',
    STOP_LIMIT: 'STOPLIMIT_ORDER',
    BEST: 'BEST_ORDER'

};
