export default {
    STOP: 'STOP',
    STOPLOSS: 'STOPLOSS',
    LIMIT: 'LIMIT',
    MARKET: 'MARKET',
    MARKETTOLIMIT: 'MARKETTOLIMIT',
    TRAILINGSTOP: 'TRAILINGSTOP',
    TRAILINGSTOPLIMIT: 'TRAILINGSTOPLIMIT',
    STOPLIMIT: 'STOPLIMIT',
    BEST: 'BEST'

};
