export default {
    SaveWatchlist: 'Save Watchlist',
    CreateNewWatchlist: 'Create New Watchlist',
    MyWatchlist: 'My Watchlist',
    Personal: 'Personal',
    SP20: 'SP20',
    SP50: 'SP50',
    SP100: 'SP100',
    SP200: 'SP200',
    TopGainers: 'TopGainers',
    TopLosers: 'TopLosers',
    TopValue: 'top-price-market-value',
    TopValueDelayed: 'top-price-market-value-delayed',
    Indices: 'Indices',
    InfoBySymbol: 'InfoBySymbol',
    Favorites: 'Favorites',
    'tradable-NYSE-01': 'tradable-NYSE-01',
    'tradable-NYSE-02': 'tradable-NYSE-02',
    'tradable-NYSE-03': 'tradable-NYSE-03',
    'tradable-NYSE-04': 'tradable-NYSE-04',
    'tradable-NYSE-05': 'tradable-NYSE-05',
    'tradable-NASDAQ-01': 'tradable-NASDAQ-01',
    'tradable-NASDAQ-02': 'tradable-NASDAQ-02',
    'tradable-NASDAQ-03': 'tradable-NASDAQ-03',
    'tradable-NASDAQ-04': 'tradable-NASDAQ-04',
    'tradable-NASDAQ-05': 'tradable-NASDAQ-05',
    'tradable-XASE': 'tradable-XASE',
    'tradable-ARCX': 'tradable-ARCX',
    NSX: 'NSX'
};
