export default {
    'MARKETTOLIMIT_MODIFY': 'MARKETTOLIMIT_MODIFY',
    'MARKET_MODIFY': 'MARKET_MODIFY',
    'STOPLOSS_MODIFY': 'STOPLOSS_MODIFY',
    'STOPLIMIT_MODIFY': 'STOPLIMIT_MODIFY',
    'LIMIT_MODIFY': 'LIMIT_MODIFY',
    'TRAILINGSTOP_MODIFY': 'TRAILINGSTOP_MODIFY',
    'STOP_MODIFY': 'STOP_MODIFY',
    'TRAILINGSTOPLIMIT_MODIFY': 'TRAILINGSTOPLIMIT_MODIFY'
}
