export default {
    'MARKET_1014': 'Market Overview',
    'MARKET_1015': 'News (Merge with Market News)',
    'MARKET_1016': 'Market News',
    'ANALYSIS_2010': 'Chart Function',
    'ANALYSIS_2011': 'Morningstar Fundamental (AUS Stock Analysis)',
    'ANALYSIS_2012': 'TipRank (US Stock Analysis)',
    'TRADING_3038': 'Watchlists',
    'TRADING_3039': 'Orders',
    'TRADING_3040': 'Depth',
    'ACCOUNT_4026': 'Portfolio (Holding)',
    'ACCOUNT_4027': 'Portfolio Summary',
    'ACCOUNT_4025': 'Account Details',
    'ACCOUNT_4028': 'Contract Notes',
    'ACCOUNT_4030': 'Activites',
    'ACCOUNT_4029': 'Reports',
    'SETTING_5008': 'Settings',
    'OPERATION_6050': 'User & Account Management',
    'OPERATION_6051': 'Saxo Clients Management',
    'OPERATION_6052': 'User & Client Management',
    'OPERATION_6053': 'Client Management',
    'OPERATION_6054': 'All Holdings',
    'OPERATION_6055': 'All Orders',
    'OPERATION_6056': 'Create New User',
    'OPERATION_6057': 'User Management	',
    'OPERATION_6058': 'User Group Management',
    'OPERATION_6059': 'Market Access Management',
    'OPERATION_6060': 'Market Data Management',
    'OPERATION_6061': 'Account Management',
    'OPERATION_6062': 'Branch Management',
    'ORDER_PAD_7012': 'New Order Pad'
}
