export const ROLE = [
    'Market / Market Overview / View Market Overview information'
    // 'Market / News / Search symbol',
    // 'Market / News / Filter News',
    // 'Market / News / Search News information',
    // 'Market / News / View News list',
    // 'Market / News / Open News',
    // 'Market / News / Download News',
    // 'Market / News / Print News',
    // 'Market / Market News / Search symbol',
    // 'Market / Market News / Filter News',
    // 'Market / Market News / Search News information',
    // 'Market / Market News / Open News',
    // 'Market / Market News / Download News',
    // 'Market / Market News / Print New',
    // 'Analysis / Charrt / Search a symbol in the Chart widget',
    // 'Analysis / Charrt / View information in the Chart widget',
    // 'Analysis / Morningstar / Search a symbol',
    // 'Analysis / Morningstar / View information in the Morningstar Tab Perfomance',
    // 'Analysis / Morningstar / View information in the Morningstar Tab Key Ratios',
    // 'Analysis / Morningstar / View information in the Morningstar Tab Financials Data',
    // 'Analysis / Morningstar / View information in the Morningstar Tab Valuations',
    // 'Analysis / Tipranks / Search a symbol',
    // 'Analysis / Tipranks / View information in the Tipranks Tab Analysts Coverage',
    // 'Analysis / Tipranks / View information in the Tipranks Tab News Sentiment',
    // 'Trading / Watchlist / View information Personal watchlist',
    // 'Trading / Watchlist / Add a symbol to the Personal watchlist',
    // 'Trading / Watchlist / Remove a symbol at the Personal watchlist',
    // 'Trading / Watchlist / Move a symbol at the Personal watchlist',
    // 'Trading / Watchlist / Filter',
    // 'Trading / Watchlist / Perform with the BUY/SELL button',
    // 'Trading / Watchlist / View Indicies watchlist',
    // 'Trading / Watchlist / View S&P 20 watchlist',
    // 'Trading / Watchlist / View S&P 50 watchlist',
    // 'Trading / Watchlist / View S&P 100 watchlist',
    // 'Trading / Watchlist / View S&P 200 watchlist',
    // 'Trading / Watchlist / View Top Gainers watchlist',
    // 'Trading / Watchlist / View Top Loser watchlist',
    // 'Trading / Watchlist / View Top Value watchlist',
    // 'Trading / Watchlist / View Tradable NASDAQ Stocks #1 watchlist',
    // 'Trading / Watchlist / View Tradable NASDAQ Stocks #2 watchlist',
    // 'Trading / Watchlist / View Tradable NYSE Stocks #1 watchlist',
    // 'Trading / Watchlist / View Tradable NYSE Stocks #2 watchlist',
    // 'Trading / Watchlist / View Tradable NYSE Stocks #3 watchlist',
    // 'Trading / Watchlist / View Tradable NYSE Stocks #4 watchlist',
    // 'Trading / Watchlist / View Tradable NYSE Stocks #5 watchlist',
    // 'Trading / Watchlist / View Tradable AMEX Stocks watchlist',
    // 'Trading / Orders / Search All Account',
    // 'Trading / Orders / Search for some Account (Account was mapping with User Login)',
    // 'Trading / Orders / Filter',
    // 'Trading / Orders / View Tab Open',
    // 'Trading / Orders / View Tab Stop Loss',
    // 'Trading / Orders / View Tab Filled',
    // 'Trading / Orders / View Tab Cancelled',
    // 'Trading / Orders / View All tab',
    // 'Trading / Orders / View Detail Order',
    // 'Trading / Orders / Perform Modify Order',
    // 'Trading / Orders / Perform Cancel Order',
    // 'Trading / Depth / Search a symbol',
    // 'Trading / Depth / View Level 1 information',
    // 'Trading / Depth / View Level 2 information ( Market Depth)',
    // 'Trading / Depth / View Course of Sales information',
    // 'Trading / Depth / Perform with the BUY/SELL button',
    // 'Account / Account Info / Search All Account',
    // 'Account / Account Info / Search for some Account (Account was mapping with User Login)',
    // 'Account / Account Info / View Account information',
    // 'Account / Porrtfolio / Search All Account',
    // 'Account / Porrtfolio / Search for some Account (Account was mapping with User Login)',
    // 'Account / Porrtfolio / View Portfolio Tab Holdings information',
    // 'Account / Porrtfolio / Filter',
    // 'Account / Porrtfolio / View Portfolio Tab Perfomance information',
    // 'Account / Porrtfolio / Perform with the New Order/Close button',
    // 'Account / Account / Search All Account',
    // 'Account / Account / Search for some Account (Account was mapping with User Login)',
    // 'Account / Account / View Account infomation',
    // 'Account / Contract Note / Search All Account',
    // 'Account / Contract Note / Search for some Account (Account was mapping with User Login)',
    // 'Account / Contract Note / Search Symbol',
    // 'Account / Contract Note / View Contract Note list',
    // 'Account / Contract Note / View Contract Note information in chronological order',
    // 'Account / Reports / Search All Account',
    // 'Account / Reports / Search for some Account (Account was mapping with User Login)',
    // 'Account / Reports / Export Financial Summary report',
    // 'Account / Reports / Export Holdings Valuation report',
    // 'Account / Reports / Export Cash Account Summary report',
    // 'Account / Reports / Export Transaction Summary report',
    // 'Account / Business Log / Filter Business Log in chronological order',
    // 'Account / Business Log / Filter ',
    // 'Settings / Set up a stocklist',
    // 'Settings / Set up Show Notifications',
    // 'Settings / Set up News Notifications status',
    // 'Settings / Set up Order Notifications status',
    // 'Settings / Set up Security ',
    // 'Settings / Change PIN',
    // 'Settings / Forgot PIN',
    // 'Operation / Saxo Clients Man / Filter',
    // 'Operation / Saxo Clients Man / Set up Trading status',
    // 'Operation / Saxo Clients Man / Change the status of all accounts to Close Positions Only',
    // 'Operation / Clients Man / Filter',
    // 'Operation / Clients Man / View the list of accounts that are mapped with the User',
    // 'Operation / User &Clients Man / View the list of User Login information',
    // 'Operation / User &Clients Man / Filter User',
    // 'Operation / User &Clients Man /  View the list of Account information',
    // 'Operation / User &Clients Man / View the Account list of a user',
    // 'Operation / User &Clients Man / Filter Account',
    // 'Operation / All Holdings / View a All holdings list of all accounts',
    // 'Operation / All Holdings / View a All holding list of some accounts (Account was mapping with User Login)',
    // 'Operation / All Holdings / Filter',
    // 'Operation / All Holdings / Filter All Account ',
    // 'Operation / All Holdings / Filter Account (Account was mapping with User Login)',
    // 'Operation / All Holdings /  Perform with the New Order button',
    // 'Operation / All Holdings /  Perform with the Close button',
    // 'Operation / All Orders / Filter',
    // 'Operation / All Orders / Filter All Account ',
    // 'Operation / All Orders / Filter Account (Account was mapping with User Login)',
    // 'Operation / All Orders / View Tab Open',
    // 'Operation / All Orders / Tab Stop Loss',
    // 'Operation / All Orders / View Tab Filled',
    // 'Operation / All Orders / View Tab Cancelled',
    // 'Operation / All Orders / View All Tab',
    // 'Operation / All Orders / View Detail Order',
    // 'Operation / All Orders / Perform Modify Order',
    // 'Operation / All Orders / Perform Cancel Order',
    // 'Operation / Create New User / View ',
    // 'Operation / Create New User / Create',
    // 'Operation / User Detail / View ',
    // 'Operation / User Detail / Edit ',
    // 'Operation / User Detail/ Resend Email or Reset Password',
    // 'Operation / User Management / View ',
    // 'Operation / User Management / Edit',
    // 'Operation / User Management / View User Detail',
    // 'Operation / User Management / View Activities',
    // 'Operation / User Management / Reset Password',
    // 'Operation / User Group Management / View',
    // 'Operation / User Group Management / Create',
    // 'Operation / User Group Management / Edit',
    // 'Operation / Market Access Management / View',
    // 'Operation / Market Access Management / View',
    // 'New Order / Open New Order Widget from Main Menu',
    // 'New Order / Search All Account Active',
    // 'New Order / Search for some Account Active (Account was mapping with User Login)',
    // 'New Order / Perform with New Order screen (Search symbol, fill price...)',
    // 'New Order / Perform with Confirm Order screen',
    // 'Modify Order / Perform with Modify Order screen',
    // 'Modify Order / Perform with Confirm Modify Order screen',
    // 'Cancel Order / Perform with Cancel Order screen',
    // 'Cancel Order / Perform with Confirm Cancel Order screen',
    // 'Order Detail / Perform with New Order button',
    // 'Order Detail / Perform with Modify Order button',
    // 'Order Detail / Perform with Cancel Order button',
    // 'What"s new / View What"s new',
    // 'Term of Use / View Term of Use'
]
