export default {
    SaveWatchlist: 'Save Watchlist',
    CreateNewWatchlist: 'Create New Watchlist',
    MyWatchlist: 'My Watchlist',
    Personal: 'Personal',
    SP20: 'SP 20',
    SP50: 'SP 50',
    SP100: 'SP 100',
    SP200: 'SP 200',
    TopGainers: 'Top Gainers',
    TopLosers: 'Top Losers',
    TopValue: 'Top Value',
    Indices: 'Indices',
    InfoBySymbol: 'InfoBySymbol',
    'tradable-NYSE-01': 'NYSE #1',
    'tradable-NYSE-02': 'NYSE #2',
    'tradable-NYSE-03': 'NYSE #3',
    'tradable-NYSE-04': 'NYSE #4',
    'tradable-NYSE-05': 'NYSE #5',
    'tradable-NASDAQ-01': 'NASDAQ #1',
    'tradable-NASDAQ-02': 'NASDAQ #2',
    'tradable-NASDAQ-03': 'NASDAQ #3',
    'tradable-NASDAQ-04': 'NASDAQ #4',
    'tradable-NASDAQ-05': 'NASDAQ #5',
    'tradable-XASE': 'AMEX',
    'tradable-ARCX': 'tradable-ARCX'
};
