export default {
  'sample-watchlist': 'Sample Watchlist',
  'user-watchlist': 'Favorites',
  'top-asx-20': 'ASX S&P 20',
  'top-asx-50': 'ASX S&P 50',
  'top-asx-100': 'ASX S&P 100',
  'top-asx-200': 'ASX S&P 200',
  'top-price-gainer': 'ASX Top Gainers',
  'top-price-gainer-delayed': 'ASX Top Gainers',
  'top-price-loser': 'ASX Top Losers',
  'top-price-loser-delayed': 'ASX Top Losers',
  'top-price-market-value': 'ASX Top Value',
  'top-price-market-value-delayed': 'ASX Top Value',
  'tradable-NASDAQ-01': 'NASDAQ #1',
  'tradable-NASDAQ-02': 'NASDAQ #2',
  'tradable-NYSE-01': 'NYSE #1',
  'tradable-NYSE-02': 'NYSE #2',
  'tradable-NYSE-03': 'NYSE #3',
  'tradable-NYSE-04': 'NYSE #4',
  'tradable-NYSE-05': 'NYSE #5',
  'tradable-XASE': 'AMEX',
  'NSX': 'NSX',
  'tradable-xkls': 'BMDX Futures',
  'tradable-xcbt': 'CBOT Futures',
  'tradable-xcec': 'COMEX Futures',
  'tradable-xcme': 'CME Futures',
  'tradable-iflx': 'ICE_EU (Agriculture) Futures',
  'tradable-ifeu': 'ICE_EU Futures',
  'tradable-ifsg': 'ICE_SG Futures',
  'tradable-ifus': 'ICE_US Futures',
  'tradable-xlme': 'LME Futures',
  'tradable-xnym': 'NYMEX Futures',
  'tradable-xsce': 'SGX Futures',
  'tradable-xtkt': 'TOCOM Futures',
  'mixed-futures': 'MIX FUTURES'
};
