
import requireTime from './constants/require_time';
import config from '../public/config'

const obj = {
    mode: null,
    timeoutNetwork: null,
    isChangePassword: false,
    closeChartLayout: {},
    isSessionAnotherLogin: false,
    dicClearRealtime: {},
    materialFont: null,
    listMapping: [],
    deviceLang: 'en_US',
    onChangeLang: null,
    dicAccounts: {},
    reloadNews: [],
    downloadFunc: {},
    printFunc: {},
    layout_role: null,
    force_update_create_user: false,
    deletingLayout: '',
    deletingChartLayout: '',
    isDragChart: false,
    isDefaultLayout: true,
    chartSelfChange: false,
    logout: null,
    isChangeLayout: false,
    curLayoutVersion: null,
    listLayout: {},
    usingLayout: '',
    curChartLayoutVersion: '1',
    listChartLayout: {},
    usingChartLayout: '',
    listUsingChartLayout: {},
    renderAfterRealtime: null,
    checkVersionLayoutBeforeOverride: null,
    isLogin: false,
    uid: null,
    isGuest: true,
    connected: true,
    full_name: null,
    accessToken: null,
    pin: null,
    user_details: null,
    user_type: 2,
    logId: 0,
    timeInterval: 0,
    isIntervalRealtime: 0,
    deviceId: 0,
    account_id: null,
    accountInfo: null,
    role: null,
    sseRegisters: {},
    handleClickOutside: null,
    typeRegisters: {},
    loginEmail: null,
    accountStreamingUrl: null,
    notify: null,
    userInfo: null,
    accounts: [],
    subPath: '',
    checkUpdate: false,
    checkLoginPin: null,
    intervalRefreshToken: null,
    intervalRefreshTokenGuest: null,
    showNotification: null,
    isShowNotification: true,
    showCancelled: false,
    showExpired: false,
    showFilled: false,
    showOnMarket: false,
    showRejected: false,
    showPartialFill: false,
    showAllNews: true,
    translate: null,
    lang: '',
    dicPersonal: {},
    dicPosition: {},
    dicNotiShowed: {},
    symbolEquity: {},
    clickedMenu: false,
    showPin: false,
    resolution: null,
    dicAccount: {},
    accountsObjDic: {},
    symbolsObjDic: {},
    pinWasChanged: false,
    symbolHistoryInfo: {},
    checkPinCallback: null,
    requireTime: requireTime.ON_CHANGE,
    verifiedPin: false,
    isStayLogin: false,
    getLayout: null,
    listFilledCancelled: {},
    dicInterval: {},
    dicLevel1: {},
    dicDepth: {},
    dicCos: {},
    dicLevel1RealTime: {},
    dicDepthRealTime: {},
    dicCosRealTime: {},
    global_symbol: null,
    listUserWatchlist: {},
    usingWatchlist: '',
    numberNoticeNews: null,
    lastSymbolSearchNews: null,
    removeSaveChartLayout: null,
    usingWatchlist_id: null,
    usingWatchlist_name: null,
    userGroupArray: [],
    userGroupDic: [], // tuanphan use
    dicEmailTemp: [],
    apiAccessDic: [],
    userGroupDicReverse: {},
    dicRole: {},
    marketData: {},
    allowDisableModifyCancelOrder: false,
    callBackReloadTheme: {},
    hrefImg: '',
    color: '#fff',
    linkColor: null,
    lstAccountDropdown: null,
    allowCloseAllWidgets: false,
    timeZone: '',
    symbolDefault: null,
    setVisibility: {},
    dicbyDisplayName: {},
    dicsymbol: {},
    watchlist: [],
    openNameWidget: '',
    symbolObjDepth: {},
    dictAccountNoti: [],
    beforeLogin: false,
    timeHoliday: {},
    isHolidayAU: {},
    isHolidayUS: {},
    timeServer: '',
    currentEnv: '',
    env_config: null,
    web_config: null,
    guest_config: null,
    isWarning: {
        isNotiTechnical: false,
        isNotiCashNegative: false
    },
    warningFunc: null,
    listFunctionInit: [],
    marketDataType: {},
    openingAccount: {},
    branchObjDic: {},
    session: {}
}

const objProxy = new Proxy(obj, {
    set: function (target, key, value) {
        // console.log(`YOLO ${key} ${target[key]} =====> ${value}`)
        target[key] = value;
        return true;
    }
})

export default objProxy
