export default [
  'Pacific/Kiritimati',
  'Pacific/Apia',
  'Pacific/Enderbury',
  'Pacific/Fakaofo',
  'Pacific/Tongatapu',
  'Pacific/Chatham',
  'Antarctica/McMurdo',
  'Asia/Anadyr',
  'Asia/Kamchatka',
  'Pacific/Auckland',
  'Pacific/Fiji',
  'Pacific/Funafuti',
  'Pacific/Kwajalein',
  'Pacific/Majuro',
  'Pacific/Nauru',
  'Pacific/Tarawa',
  'Pacific/Wake',
  'Pacific/Wallis',
  'Antarctica/Macquarie',
  'Asia/Magadan',
  'Asia/Sakhalin',
  'Asia/Srednekolymsk',
  'Pacific/Bougainville',
  'Pacific/Efate',
  'Pacific/Guadalcanal',
  'Pacific/Kosrae',
  'Pacific/Norfolk',
  'Pacific/Noumea',
  'Pacific/Pohnpei',
  'Australia/Lord_Howe',
  'Antarctica/DumontDUrville',
  'Asia/Ust-Nera',
  'Asia/Vladivostok',
  'Australia/Brisbane',
  'Australia/Currie',
  'Australia/Hobart',
  'Australia/Lindeman',
  'Australia/Melbourne',
  'Australia/Sydney',
  'Pacific/Chuuk',
  'Pacific/Guam',
  'Pacific/Port_Moresby',
  'Pacific/Saipan',
  'Australia/Adelaide',
  'Australia/Broken_Hill',
  'Australia/Darwin',
  'Asia/Chita',
  'Asia/Dili',
  'Asia/Jayapura',
  'Asia/Khandyga',
  'Asia/Pyongyang',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Asia/Yakutsk',
  'Pacific/Palau',
  'Australia/Eucla',
  'Antarctica/Casey',
  'Asia/Brunei',
  'Asia/Choibalsan',
  'Asia/Hong_Kong',
  'Asia/Irkutsk',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Asia/Macau',
  'Asia/Makassar',
  'Asia/Manila',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Taipei',
  'Asia/Ulaanbaatar',
  'Australia/Perth',
  'Antarctica/Davis',
  'Asia/Bangkok',
  'Asia/Barnaul',
  'Asia/Ho_Chi_Minh',
  'Asia/Hovd',
  'Asia/Jakarta',
  'Asia/Krasnoyarsk',
  'Asia/Novokuznetsk',
  'Asia/Novosibirsk',
  'Asia/Phnom_Penh',
  'Asia/Pontianak',
  'Asia/Tomsk',
  'Asia/Vientiane',
  'Indian/Christmas',
  'Asia/Yangon',
  'Indian/Cocos',
  'Antarctica/Vostok',
  'Asia/Almaty',
  'Asia/Bishkek',
  'Asia/Dhaka',
  'Asia/Omsk',
  'Asia/Qyzylorda',
  'Asia/Thimphu',
  'Asia/Urumqi',
  'Indian/Chagos',
  'Asia/Kathmandu',
  'Asia/Colombo',
  'Asia/Kolkata',
  'Antarctica/Mawson',
  'Asia/Aqtau',
  'Asia/Aqtobe',
  'Asia/Ashgabat',
  'Asia/Atyrau',
  'Asia/Dushanbe',
  'Asia/Karachi',
  'Asia/Oral',
  'Asia/Samarkand',
  'Asia/Tashkent',
  'Asia/Yekaterinburg',
  'Indian/Kerguelen',
  'Indian/Maldives',
  'Asia/Kabul',
  'Asia/Tehran',
  'Asia/Baku',
  'Asia/Dubai',
  'Asia/Muscat',
  'Asia/Tbilisi',
  'Asia/Yerevan',
  'Europe/Astrakhan',
  'Europe/Samara',
  'Europe/Saratov',
  'Europe/Ulyanovsk',
  'Europe/Volgograd',
  'Indian/Mahe',
  'Indian/Mauritius',
  'Indian/Reunion',
  'Africa/Addis_Ababa',
  'Africa/Asmara',
  'Africa/Dar_es_Salaam',
  'Africa/Djibouti',
  'Africa/Juba',
  'Africa/Kampala',
  'Africa/Mogadishu',
  'Africa/Nairobi',
  'Antarctica/Syowa',
  'Asia/Aden',
  'Asia/Amman',
  'Asia/Baghdad',
  'Asia/Bahrain',
  'Asia/Beirut',
  'Asia/Damascus',
  'Asia/Famagusta',
  'Asia/Gaza',
  'Asia/Hebron',
  'Asia/Jerusalem',
  'Asia/Kuwait',
  'Asia/Nicosia',
  'Asia/Qatar',
  'Asia/Riyadh',
  'Europe/Athens',
  'Europe/Bucharest',
  'Europe/Chisinau',
  'Europe/Helsinki',
  'Europe/Istanbul',
  'Europe/Kiev',
  'Europe/Kirov',
  'Europe/Mariehamn',
  'Europe/Minsk',
  'Europe/Moscow',
  'Europe/Riga',
  'Europe/Simferopol',
  'Europe/Sofia',
  'Europe/Tallinn',
  'Europe/Uzhgorod',
  'Europe/Vilnius',
  'Europe/Zaporozhye',
  'Indian/Antananarivo',
  'Indian/Comoro',
  'Indian/Mayotte',
  'Africa/Blantyre',
  'Africa/Bujumbura',
  'Africa/Cairo',
  'Africa/Ceuta',
  'Africa/Gaborone',
  'Africa/Harare',
  'Africa/Johannesburg',
  'Africa/Khartoum',
  'Africa/Kigali',
  'Africa/Lubumbashi',
  'Africa/Lusaka',
  'Africa/Maputo',
  'Africa/Maseru',
  'Africa/Mbabane',
  'Africa/Tripoli',
  'Africa/Windhoek',
  'Antarctica/Troll',
  'Arctic/Longyearbyen',
  'Europe/Amsterdam',
  'Europe/Andorra',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/Bratislava',
  'Europe/Brussels',
  'Europe/Budapest',
  'Europe/Busingen',
  'Europe/Copenhagen',
  'Europe/Gibraltar',
  'Europe/Kaliningrad',
  'Europe/Ljubljana',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Malta',
  'Europe/Monaco',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Podgorica',
  'Europe/Prague',
  'Europe/Rome',
  'Europe/San_Marino',
  'Europe/Sarajevo',
  'Europe/Skopje',
  'Europe/Stockholm',
  'Europe/Tirane',
  'Europe/Vaduz',
  'Europe/Vatican',
  'Europe/Vienna',
  'Europe/Warsaw',
  'Europe/Zagreb',
  'Europe/Zurich',
  'Africa/Algiers',
  'Africa/Bangui',
  'Africa/Brazzaville',
  'Africa/Casablanca',
  'Africa/Douala',
  'Africa/El_Aaiun',
  'Africa/Kinshasa',
  'Africa/Lagos',
  'Africa/Libreville',
  'Africa/Luanda',
  'Africa/Malabo',
  'Africa/Ndjamena',
  'Africa/Niamey',
  'Africa/Porto-Novo',
  'Africa/Sao_Tome',
  'Africa/Tunis',
  'Atlantic/Canary',
  'Atlantic/Faroe',
  'Atlantic/Madeira',
  'Europe/Dublin',
  'Europe/Guernsey',
  'Europe/Isle_of_Man',
  'Europe/Jersey',
  'Europe/Lisbon',
  'Europe/London',
  'Africa/Abidjan',
  'Africa/Accra',
  'Africa/Bamako',
  'Africa/Banjul',
  'Africa/Bissau',
  'Africa/Conakry',
  'Africa/Dakar',
  'Africa/Freetown',
  'Africa/Lome',
  'Africa/Monrovia',
  'Africa/Nouakchott',
  'Africa/Ouagadougou',
  'America/Danmarkshavn',
  'America/Scoresbysund',
  'Atlantic/Azores',
  'Atlantic/Reykjavik',
  'Atlantic/St_Helena',
  'UTC',
  'Atlantic/Cape_Verde',
  'America/Godthab',
  'America/Miquelon',
  'America/Noronha',
  'Atlantic/South_Georgia',
  'America/St_Johns',
  'America/Araguaina',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Catamarca',
  'America/Argentina/Cordoba',
  'America/Argentina/Jujuy',
  'America/Argentina/La_Rioja',
  'America/Argentina/Mendoza',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta',
  'America/Argentina/San_Juan',
  'America/Argentina/San_Luis',
  'America/Argentina/Tucuman',
  'America/Argentina/Ushuaia',
  'America/Bahia',
  'America/Belem',
  'America/Cayenne',
  'America/Fortaleza',
  'America/Glace_Bay',
  'America/Goose_Bay',
  'America/Halifax',
  'America/Maceio',
  'America/Moncton',
  'America/Montevideo',
  'America/Paramaribo',
  'America/Punta_Arenas',
  'America/Recife',
  'America/Santarem',
  'America/Sao_Paulo',
  'America/Thule',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Atlantic/Bermuda',
  'Atlantic/Stanley',
  'America/Anguilla',
  'America/Antigua',
  'America/Aruba',
  'America/Asuncion',
  'America/Barbados',
  'America/Blanc-Sablon',
  'America/Boa_Vista',
  'America/Campo_Grande',
  'America/Caracas',
  'America/Cuiaba',
  'America/Curacao',
  'America/Detroit',
  'America/Dominica',
  'America/Grand_Turk',
  'America/Grenada',
  'America/Guadeloupe',
  'America/Guyana',
  'America/Havana',
  'America/Indiana/Indianapolis',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Vevay',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Iqaluit',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/Kralendijk',
  'America/La_Paz',
  'America/Lower_Princes',
  'America/Manaus',
  'America/Marigot',
  'America/Martinique',
  'America/Montserrat',
  'America/Nassau',
  'America/New_York',
  'America/Nipigon',
  'America/Pangnirtung',
  'America/Port-au-Prince',
  'America/Port_of_Spain',
  'America/Porto_Velho',
  'America/Puerto_Rico',
  'America/Santiago',
  'America/Santo_Domingo',
  'America/St_Barthelemy',
  'America/St_Kitts',
  'America/St_Lucia',
  'America/St_Thomas',
  'America/St_Vincent',
  'America/Thunder_Bay',
  'America/Toronto',
  'America/Tortola',
  'America/Atikokan',
  'America/Bahia_Banderas',
  'America/Bogota',
  'America/Cancun',
  'America/Cayman',
  'America/Chicago',
  'America/Eirunepe',
  'America/Guayaquil',
  'America/Indiana/Knox',
  'America/Indiana/Tell_City',
  'America/Jamaica',
  'America/Lima',
  'America/Matamoros',
  'America/Menominee',
  'America/Merida',
  'America/Mexico_City',
  'America/Monterrey',
  'America/North_Dakota/Beulah',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'America/Panama',
  'America/Rainy_River',
  'America/Rankin_Inlet',
  'America/Resolute',
  'America/Rio_Branco',
  'America/Winnipeg',
  'America/Belize',
  'America/Boise',
  'America/Cambridge_Bay',
  'America/Chihuahua',
  'America/Costa_Rica',
  'America/Denver',
  'America/Edmonton',
  'America/El_Salvador',
  'America/Guatemala',
  'America/Inuvik',
  'America/Managua',
  'America/Mazatlan',
  'America/Ojinaga',
  'America/Regina',
  'America/Swift_Current',
  'America/Tegucigalpa',
  'America/Yellowknife',
  'Pacific/Easter',
  'Pacific/Galapagos',
  'America/Creston',
  'America/Dawson',
  'America/Dawson_Creek',
  'America/Fort_Nelson',
  'America/Hermosillo',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Tijuana',
  'America/Vancouver',
  'America/Whitehorse',
  'America/Anchorage',
  'America/Juneau',
  'America/Metlakatla',
  'America/Nome',
  'America/Sitka',
  'America/Yakutat',
  'Pacific/Pitcairn',
  'America/Adak',
  'Pacific/Gambier',
  'Pacific/Marquesas',
  'Pacific/Honolulu',
  'Pacific/Rarotonga',
  'Pacific/Tahiti',
  'Pacific/Midway',
  'Pacific/Niue',
  'Pacific/Pago_Pago'
]

export const DisplayTimeZone = {
  'Africa/Abidjan': 'Africa, Abidjan',
  'Africa/Accra': 'Africa, Accra',
  'Africa/Addis_Ababa': 'Africa, Addis Ababa',
  'Africa/Algiers': 'Africa, Algiers',
  'Africa/Asmara': 'Africa, Asmara',
  'Africa/Bamako': 'Africa, Bamako',
  'Africa/Bangui': 'Africa, Bangui',
  'Africa/Banjul': 'Africa, Banjul',
  'Africa/Bissau': 'Africa, Bissau',
  'Africa/Blantyre': 'Africa, Blantyre',
  'Africa/Brazzaville': 'Africa, Brazzaville',
  'Africa/Bujumbura': 'Africa, Bujumbura',
  'Africa/Cairo': 'Africa, Cairo',
  'Africa/Casablanca': 'Africa, Casablanca',
  'Africa/Ceuta': 'Africa, Ceuta',
  'Africa/Conakry': 'Africa, Conakry',
  'Africa/Dakar': 'Africa, Dakar',
  'Africa/Dar_es_Salaam': 'Africa, Dar es Salaam',
  'Africa/Djibouti': 'Africa, Djibouti',
  'Africa/Douala': 'Africa, Douala',
  'Africa/El_Aaiun': 'Africa, El Aaiun',
  'Africa/Freetown': 'Africa, Freetown',
  'Africa/Gaborone': 'Africa, Gaborone',
  'Africa/Harare': 'Africa, Harare',
  'Africa/Johannesburg': 'Africa, Johannesburg',
  'Africa/Juba': 'Africa, Juba',
  'Africa/Kampala': 'Africa, Kampala',
  'Africa/Khartoum': 'Africa, Khartoum',
  'Africa/Kigali': 'Africa, Kigali',
  'Africa/Kinshasa': 'Africa, Kinshasa',
  'Africa/Lagos': 'Africa, Lagos',
  'Africa/Libreville': 'Africa, Libreville',
  'Africa/Lome': 'Africa, Lome',
  'Africa/Luanda': 'Africa, Luanda',
  'Africa/Lubumbashi': 'Africa, Lubumbashi',
  'Africa/Lusaka': 'Africa, Lusaka',
  'Africa/Malabo': 'Africa, Malabo',
  'Africa/Maputo': 'Africa, Maputo',
  'Africa/Maseru': 'Africa, Maseru',
  'Africa/Mbabane': 'Africa, Mbabane',
  'Africa/Mogadishu': 'Africa, Mogadishu',
  'Africa/Monrovia': 'Africa, Monrovia',
  'Africa/Nairobi': 'Africa, Nairobi',
  'Africa/Ndjamena': 'Africa, Ndjamena',
  'Africa/Niamey': 'Africa, Niamey',
  'Africa/Nouakchott': 'Africa, Nouakchott',
  'Africa/Ouagadougou': 'Africa, Ouagadougou',
  'Africa/Porto-Novo': 'Africa, Porto-Novo',
  'Africa/Sao_Tome': 'Africa, Sao Tome',
  'Africa/Tripoli': 'Africa, Tripoli',
  'Africa/Tunis': 'Africa, Tunis',
  'Africa/Windhoek': 'Africa, Windhoek',
  'America/Adak': 'America, Adak',
  'America/Anchorage': 'America, Anchorage',
  'America/Anguilla': 'America, Anguilla',
  'America/Antigua': 'America, Antigua',
  'America/Araguaina': 'America, Araguaina',
  'America/Argentina/Buenos_Aires': 'America, Argentina, Buenos Aires',
  'America/Argentina/Catamarca': 'America, Argentina, Catamarca',
  'America/Argentina/Cordoba': 'America, Argentina, Cordoba',
  'America/Argentina/Jujuy': 'America, Argentina, Jujuy',
  'America/Argentina/La_Rioja': 'America, Argentina, La Rioja',
  'America/Argentina/Mendoza': 'America, Argentina, Mendoza',
  'America/Argentina/Rio_Gallegos': 'America, Argentina, Rio Gallegos',
  'America/Argentina/Salta': 'America, Argentina, Salta',
  'America/Argentina/San_Juan': 'America, Argentina, San Juan',
  'America/Argentina/San_Luis': 'America, Argentina, San Luis',
  'America/Argentina/Tucuman': 'America, Argentina, Tucuman',
  'America/Argentina/Ushuaia': 'America, Argentina, Ushuaia',
  'America/Aruba': 'America, Aruba',
  'America/Asuncion': 'America, Asuncion',
  'America/Atikokan': 'America, Atikokan',
  'America/Bahia': 'America, Bahia',
  'America/Bahia_Banderas': 'America, Bahia Banderas',
  'America/Barbados': 'America, Barbados',
  'America/Belem': 'America, Belem',
  'America/Belize': 'America, Belize',
  'America/Blanc-Sablon': 'America, Blanc-Sablon',
  'America/Boa_Vista': 'America, Boa Vista',
  'America/Bogota': 'America, Bogota',
  'America/Boise': 'America, Boise',
  'America/Cambridge_Bay': 'America, Cambridge Bay',
  'America/Campo_Grande': 'America, Campo Grande',
  'America/Cancun': 'America, Cancun',
  'America/Caracas': 'America, Caracas',
  'America/Cayenne': 'America, Cayenne',
  'America/Cayman': 'America, Cayman',
  'America/Chicago': 'America, Chicago',
  'America/Chihuahua': 'America, Chihuahua',
  'America/Costa_Rica': 'America, Costa Rica',
  'America/Creston': 'America, Creston',
  'America/Cuiaba': 'America, Cuiaba',
  'America/Curacao': 'America, Curacao',
  'America/Danmarkshavn': 'America, Danmarkshavn',
  'America/Dawson': 'America, Dawson',
  'America/Dawson_Creek': 'America, Dawson Creek',
  'America/Denver': 'America, Denver',
  'America/Detroit': 'America, Detroit',
  'America/Dominica': 'America, Dominica',
  'America/Edmonton': 'America, Edmonton',
  'America/Eirunepe': 'America, Eirunepe',
  'America/El_Salvador': 'America, El Salvador',
  'America/Fort_Nelson': 'America, Fort Nelson',
  'America/Fortaleza': 'America, Fortaleza',
  'America/Glace_Bay': 'America, Glace Bay',
  'America/Godthab': 'America, Godthab',
  'America/Goose_Bay': 'America, Goose Bay',
  'America/Grand_Turk': 'America, Grand Turk',
  'America/Grenada': 'America, Grenada',
  'America/Guadeloupe': 'America, Guadeloupe',
  'America/Guatemala': 'America, Guatemala',
  'America/Guayaquil': 'America, Guayaquil',
  'America/Guyana': 'America, Guyana',
  'America/Halifax': 'America, Halifax',
  'America/Havana': 'America, Havana',
  'America/Hermosillo': 'America, Hermosillo',
  'America/Indiana/Indianapolis': 'America, Indiana, Indianapolis',
  'America/Indiana/Knox': 'America, Indiana, Knox',
  'America/Indiana/Marengo': 'America, Indiana, Marengo',
  'America/Indiana/Petersburg': 'America, Indiana, Petersburg',
  'America/Indiana/Tell_City': 'America, Indiana, Tell City',
  'America/Indiana/Vevay': 'America, Indiana, Vevay',
  'America/Indiana/Vincennes': 'America, Indiana, Vincennes',
  'America/Indiana/Winamac': 'America, Indiana, Winamac',
  'America/Inuvik': 'America, Inuvik',
  'America/Iqaluit': 'America, Iqaluit',
  'America/Jamaica': 'America, Jamaica',
  'America/Juneau': 'America, Juneau',
  'America/Kentucky/Louisville': 'America, Kentucky, Louisville',
  'America/Kentucky/Monticello': 'America, Kentucky, Monticello',
  'America/Kralendijk': 'America, Kralendijk',
  'America/La_Paz': 'America, La Paz',
  'America/Lima': 'America, Lima',
  'America/Los_Angeles': 'America, Los Angeles',
  'America/Lower_Princes': 'America, Lower Princes',
  'America/Maceio': 'America, Maceio',
  'America/Managua': 'America, Managua',
  'America/Manaus': 'America, Manaus',
  'America/Marigot': 'America, Marigot',
  'America/Martinique': 'America, Martinique',
  'America/Matamoros': 'America, Matamoros',
  'America/Mazatlan': 'America, Mazatlan',
  'America/Menominee': 'America, Menominee',
  'America/Merida': 'America, Merida',
  'America/Metlakatla': 'America, Metlakatla',
  'America/Mexico_City': 'America, Mexico City',
  'America/Miquelon': 'America, Miquelon',
  'America/Moncton': 'America, Moncton',
  'America/Monterrey': 'America, Monterrey',
  'America/Montevideo': 'America, Montevideo',
  'America/Montserrat': 'America, Montserrat',
  'America/Nassau': 'America, Nassau',
  'America/New_York': 'America, New York',
  'America/Nipigon': 'America, Nipigon',
  'America/Nome': 'America, Nome',
  'America/Noronha': 'America, Noronha',
  'America/North_Dakota/Beulah': 'America, North Dakota, Beulah',
  'America/North_Dakota/Center': 'America, North Dakota, Center',
  'America/North_Dakota/New_Salem': 'America, North Dakota, New Salem',
  'America/Ojinaga': 'America, Ojinaga',
  'America/Panama': 'America, Panama',
  'America/Pangnirtung': 'America, Pangnirtung',
  'America/Paramaribo': 'America, Paramaribo',
  'America/Phoenix': 'America, Phoenix',
  'America/Port-au-Prince': 'America, Port-au-Prince',
  'America/Port_of_Spain': 'America, Port of Spain',
  'America/Porto_Velho': 'America, Porto Velho',
  'America/Puerto_Rico': 'America, Puerto Rico',
  'America/Punta_Arenas': 'America, Punta Arenas',
  'America/Rainy_River': 'America, Rainy River',
  'America/Rankin_Inlet': 'America, Rankin Inlet',
  'America/Recife': 'America, Recife',
  'America/Regina': 'America, Regina',
  'America/Resolute': 'America, Resolute',
  'America/Rio_Branco': 'America, Rio Branco',
  'America/Santarem': 'America, Santarem',
  'America/Santiago': 'America, Santiago',
  'America/Santo_Domingo': 'America, Santo Domingo',
  'America/Sao_Paulo': 'America, Sao Paulo',
  'America/Scoresbysund': 'America, Scoresbysund',
  'America/Sitka': 'America, Sitka',
  'America/St_Barthelemy': 'America, St Barthelemy',
  'America/St_Johns': 'America, St Johns',
  'America/St_Kitts': 'America, St Kitts',
  'America/St_Lucia': 'America, St Lucia',
  'America/St_Thomas': 'America, St Thomas',
  'America/St_Vincent': 'America, St Vincent',
  'America/Swift_Current': 'America, Swift Current',
  'America/Tegucigalpa': 'America, Tegucigalpa',
  'America/Thule': 'America, Thule',
  'America/Thunder_Bay': 'America, Thunder Bay',
  'America/Tijuana': 'America, Tijuana',
  'America/Toronto': 'America, Toronto',
  'America/Tortola': 'America, Tortola',
  'America/Vancouver': 'America, Vancouver',
  'America/Whitehorse': 'America, Whitehorse',
  'America/Winnipeg': 'America, Winnipeg',
  'America/Yakutat': 'America, Yakutat',
  'America/Yellowknife': 'America, Yellowknife',
  'Antarctica/Casey': 'Antarctica, Casey',
  'Antarctica/Davis': 'Antarctica, Davis',
  'Antarctica/DumontDUrville': 'Antarctica, DumontDUrville',
  'Antarctica/Macquarie': 'Antarctica, Macquarie',
  'Antarctica/Mawson': 'Antarctica, Mawson',
  'Antarctica/McMurdo': 'Antarctica, McMurdo',
  'Antarctica/Palmer': 'Antarctica, Palmer',
  'Antarctica/Rothera': 'Antarctica, Rothera',
  'Antarctica/Syowa': 'Antarctica, Syowa',
  'Antarctica/Troll': 'Antarctica, Troll',
  'Antarctica/Vostok': 'Antarctica, Vostok',
  'Arctic/Longyearbyen': 'Arctic, Longyearbyen',
  'Asia/Aden': 'Asia, Aden',
  'Asia/Almaty': 'Asia, Almaty',
  'Asia/Amman': 'Asia, Amman',
  'Asia/Anadyr': 'Asia, Anadyr',
  'Asia/Aqtau': 'Asia, Aqtau',
  'Asia/Aqtobe': 'Asia, Aqtobe',
  'Asia/Ashgabat': 'Asia, Ashgabat',
  'Asia/Atyrau': 'Asia, Atyrau',
  'Asia/Baghdad': 'Asia, Baghdad',
  'Asia/Bahrain': 'Asia, Bahrain',
  'Asia/Baku': 'Asia, Baku',
  'Asia/Bangkok': 'Asia, Bangkok',
  'Asia/Barnaul': 'Asia, Barnaul',
  'Asia/Beirut': 'Asia, Beirut',
  'Asia/Bishkek': 'Asia, Bishkek',
  'Asia/Brunei': 'Asia, Brunei',
  'Asia/Chita': 'Asia, Chita',
  'Asia/Choibalsan': 'Asia, Choibalsan',
  'Asia/Colombo': 'Asia, Colombo',
  'Asia/Damascus': 'Asia, Damascus',
  'Asia/Dhaka': 'Asia, Dhaka',
  'Asia/Dili': 'Asia, Dili',
  'Asia/Dubai': 'Asia, Dubai',
  'Asia/Dushanbe': 'Asia, Dushanbe',
  'Asia/Famagusta': 'Asia, Famagusta',
  'Asia/Gaza': 'Asia, Gaza',
  'Asia/Hebron': 'Asia, Hebron',
  'Asia/Ho_Chi_Minh': 'Asia, Ho Chi Minh',
  'Asia/Hong_Kong': 'Asia, Hong Kong',
  'Asia/Hovd': 'Asia, Hovd',
  'Asia/Irkutsk': 'Asia, Irkutsk',
  'Asia/Jakarta': 'Asia, Jakarta',
  'Asia/Jayapura': 'Asia, Jayapura',
  'Asia/Jerusalem': 'Asia, Jerusalem',
  'Asia/Kabul': 'Asia, Kabul',
  'Asia/Kamchatka': 'Asia, Kamchatka',
  'Asia/Karachi': 'Asia, Karachi',
  'Asia/Kathmandu': 'Asia, Kathmandu',
  'Asia/Khandyga': 'Asia, Khandyga',
  'Asia/Kolkata': 'Asia, Kolkata',
  'Asia/Krasnoyarsk': 'Asia, Krasnoyarsk',
  'Asia/Kuala_Lumpur': 'Asia, Kuala Lumpur',
  'Asia/Kuching': 'Asia, Kuching',
  'Asia/Kuwait': 'Asia, Kuwait',
  'Asia/Macau': 'Asia, Macau',
  'Asia/Magadan': 'Asia, Magadan',
  'Asia/Makassar': 'Asia, Makassar',
  'Asia/Manila': 'Asia, Manila',
  'Asia/Muscat': 'Asia, Muscat',
  'Asia/Nicosia': 'Asia, Nicosia',
  'Asia/Novokuznetsk': 'Asia, Novokuznetsk',
  'Asia/Novosibirsk': 'Asia, Novosibirsk',
  'Asia/Omsk': 'Asia, Omsk',
  'Asia/Oral': 'Asia, Oral',
  'Asia/Phnom_Penh': 'Asia, Phnom Penh',
  'Asia/Pontianak': 'Asia, Pontianak',
  'Asia/Pyongyang': 'Asia, Pyongyang',
  'Asia/Qatar': 'Asia, Qatar',
  'Asia/Qyzylorda': 'Asia, Qyzylorda',
  'Asia/Riyadh': 'Asia, Riyadh',
  'Asia/Sakhalin': 'Asia, Sakhalin',
  'Asia/Samarkand': 'Asia, Samarkand',
  'Asia/Seoul': 'Asia, Seoul',
  'Asia/Shanghai': 'Asia, Shanghai',
  'Asia/Singapore': 'Asia, Singapore',
  'Asia/Srednekolymsk': 'Asia, Srednekolymsk',
  'Asia/Taipei': 'Asia, Taipei',
  'Asia/Tashkent': 'Asia, Tashkent',
  'Asia/Tbilisi': 'Asia, Tbilisi',
  'Asia/Tehran': 'Asia, Tehran',
  'Asia/Thimphu': 'Asia, Thimphu',
  'Asia/Tokyo': 'Asia, Tokyo',
  'Asia/Tomsk': 'Asia, Tomsk',
  'Asia/Ulaanbaatar': 'Asia, Ulaanbaatar',
  'Asia/Urumqi': 'Asia, Urumqi',
  'Asia/Ust-Nera': 'Asia, Ust-Nera',
  'Asia/Vientiane': 'Asia, Vientiane',
  'Asia/Vladivostok': 'Asia, Vladivostok',
  'Asia/Yakutsk': 'Asia, Yakutsk',
  'Asia/Yangon': 'Asia, Yangon',
  'Asia/Yekaterinburg': 'Asia, Yekaterinburg',
  'Asia/Yerevan': 'Asia, Yerevan',
  'Atlantic/Azores': 'Atlantic, Azores',
  'Atlantic/Bermuda': 'Atlantic, Bermuda',
  'Atlantic/Canary': 'Atlantic, Canary',
  'Atlantic/Cape_Verde': 'Atlantic, Cape Verde',
  'Atlantic/Faroe': 'Atlantic, Faroe',
  'Atlantic/Madeira': 'Atlantic, Madeira',
  'Atlantic/Reykjavik': 'Atlantic, Reykjavik',
  'Atlantic/South_Georgia': 'Atlantic, South Georgia',
  'Atlantic/St_Helena': 'Atlantic, St Helena',
  'Atlantic/Stanley': 'Atlantic, Stanley',
  'Australia/Adelaide': 'Australia, Adelaide',
  'Australia/Brisbane': 'Australia, Brisbane',
  'Australia/Broken_Hill': 'Australia, Broken Hill',
  'Australia/Currie': 'Australia, Currie',
  'Australia/Darwin': 'Australia, Darwin',
  'Australia/Eucla': 'Australia, Eucla',
  'Australia/Hobart': 'Australia, Hobart',
  'Australia/Lindeman': 'Australia, Lindeman',
  'Australia/Lord_Howe': 'Australia, Lord Howe',
  'Australia/Melbourne': 'Australia, Melbourne',
  'Australia/Perth': 'Australia, Perth',
  'Australia/Sydney': 'Australia, Sydney',
  'Europe/Amsterdam': 'Europe, Amsterdam',
  'Europe/Andorra': 'Europe, Andorra',
  'Europe/Astrakhan': 'Europe, Astrakhan',
  'Europe/Athens': 'Europe, Athens',
  'Europe/Belgrade': 'Europe, Belgrade',
  'Europe/Berlin': 'Europe, Berlin',
  'Europe/Bratislava': 'Europe, Bratislava',
  'Europe/Brussels': 'Europe, Brussels',
  'Europe/Bucharest': 'Europe, Bucharest',
  'Europe/Budapest': 'Europe, Budapest',
  'Europe/Busingen': 'Europe, Busingen',
  'Europe/Chisinau': 'Europe, Chisinau',
  'Europe/Copenhagen': 'Europe, Copenhagen',
  'Europe/Dublin': 'Europe, Dublin',
  'Europe/Gibraltar': 'Europe, Gibraltar',
  'Europe/Guernsey': 'Europe, Guernsey',
  'Europe/Helsinki': 'Europe, Helsinki',
  'Europe/Isle_of_Man': 'Europe, Isle of Man',
  'Europe/Istanbul': 'Europe, Istanbul',
  'Europe/Jersey': 'Europe, Jersey',
  'Europe/Kaliningrad': 'Europe, Kaliningrad',
  'Europe/Kiev': 'Europe, Kiev',
  'Europe/Kirov': 'Europe, Kirov',
  'Europe/Lisbon': 'Europe, Lisbon',
  'Europe/Ljubljana': 'Europe, Ljubljana',
  'Europe/London': 'Europe, London',
  'Europe/Luxembourg': 'Europe, Luxembourg',
  'Europe/Madrid': 'Europe, Madrid',
  'Europe/Malta': 'Europe, Malta',
  'Europe/Mariehamn': 'Europe, Mariehamn',
  'Europe/Minsk': 'Europe, Minsk',
  'Europe/Monaco': 'Europe, Monaco',
  'Europe/Moscow': 'Europe, Moscow',
  'Europe/Oslo': 'Europe, Oslo',
  'Europe/Paris': 'Europe, Paris',
  'Europe/Podgorica': 'Europe, Podgorica',
  'Europe/Prague': 'Europe, Prague',
  'Europe/Riga': 'Europe, Riga',
  'Europe/Rome': 'Europe, Rome',
  'Europe/Samara': 'Europe, Samara',
  'Europe/San_Marino': 'Europe, San Marino',
  'Europe/Sarajevo': 'Europe, Sarajevo',
  'Europe/Saratov': 'Europe, Saratov',
  'Europe/Simferopol': 'Europe, Simferopol',
  'Europe/Skopje': 'Europe, Skopje',
  'Europe/Sofia': 'Europe, Sofia',
  'Europe/Stockholm': 'Europe, Stockholm',
  'Europe/Tallinn': 'Europe, Tallinn',
  'Europe/Tirane': 'Europe, Tirane',
  'Europe/Ulyanovsk': 'Europe, Ulyanovsk',
  'Europe/Uzhgorod': 'Europe, Uzhgorod',
  'Europe/Vaduz': 'Europe, Vaduz',
  'Europe/Vatican': 'Europe, Vatican',
  'Europe/Vienna': 'Europe, Vienna',
  'Europe/Vilnius': 'Europe, Vilnius',
  'Europe/Volgograd': 'Europe, Volgograd',
  'Europe/Warsaw': 'Europe, Warsaw',
  'Europe/Zagreb': 'Europe, Zagreb',
  'Europe/Zaporozhye': 'Europe, Zaporozhye',
  'Europe/Zurich': 'Europe, Zurich',
  'Indian/Antananarivo': 'Indian, Antananarivo',
  'Indian/Chagos': 'Indian, Chagos',
  'Indian/Christmas': 'Indian, Christmas',
  'Indian/Cocos': 'Indian, Cocos',
  'Indian/Comoro': 'Indian, Comoro',
  'Indian/Kerguelen': 'Indian, Kerguelen',
  'Indian/Mahe': 'Indian, Mahe',
  'Indian/Maldives': 'Indian, Maldives',
  'Indian/Mauritius': 'Indian, Mauritius',
  'Indian/Mayotte': 'Indian, Mayotte',
  'Indian/Reunion': 'Indian, Reunion',
  'Pacific/Apia': 'Pacific, Apia',
  'Pacific/Auckland': 'Pacific, Auckland',
  'Pacific/Bougainville': 'Pacific, Bougainville',
  'Pacific/Chatham': 'Pacific, Chatham',
  'Pacific/Chuuk': 'Pacific, Chuuk',
  'Pacific/Easter': 'Pacific, Easter',
  'Pacific/Efate': 'Pacific, Efate',
  'Pacific/Enderbury': 'Pacific, Enderbury',
  'Pacific/Fakaofo': 'Pacific, Fakaofo',
  'Pacific/Fiji': 'Pacific, Fiji',
  'Pacific/Funafuti': 'Pacific, Funafuti',
  'Pacific/Galapagos': 'Pacific, Galapagos',
  'Pacific/Gambier': 'Pacific, Gambier',
  'Pacific/Guadalcanal': 'Pacific, Guadalcanal',
  'Pacific/Guam': 'Pacific, Guam',
  'Pacific/Honolulu': 'Pacific, Honolulu',
  'Pacific/Kiritimati': 'Pacific, Kiritimati',
  'Pacific/Kosrae': 'Pacific, Kosrae',
  'Pacific/Kwajalein': 'Pacific, Kwajalein',
  'Pacific/Majuro': 'Pacific, Majuro',
  'Pacific/Marquesas': 'Pacific, Marquesas',
  'Pacific/Midway': 'Pacific, Midway',
  'Pacific/Nauru': 'Pacific, Nauru',
  'Pacific/Niue': 'Pacific, Niue',
  'Pacific/Norfolk': 'Pacific, Norfolk',
  'Pacific/Noumea': 'Pacific, Noumea',
  'Pacific/Pago_Pago': 'Pacific, Pago Pago',
  'Pacific/Palau': 'Pacific, Palau',
  'Pacific/Pitcairn': 'Pacific, Pitcairn',
  'Pacific/Pohnpei': 'Pacific, Pohnpei',
  'Pacific/Port_Moresby': 'Pacific, Port Moresby',
  'Pacific/Rarotonga': 'Pacific, Rarotonga',
  'Pacific/Saipan': 'Pacific, Saipan',
  'Pacific/Tahiti': 'Pacific, Tahiti',
  'Pacific/Tarawa': 'Pacific, Tarawa',
  'Pacific/Tongatapu': 'Pacific, Tongatapu',
  'Pacific/Wake': 'Pacific, Wake',
  'Pacific/Wallis': 'Pacific, Wallis'
}
